import './globals.css';
import 'dayjs/locale/ko';
import dayjs from 'dayjs';
import { type Metadata } from 'next';
import localFont from 'next/font/local';
import { CoreProvider, MODAL_COMPONENTS } from '@/app';
import { Modal } from '@/features/modal';
import { Footer } from '@/widgets/footer';

dayjs.locale('ko');

const pretendard = localFont({
  src: '../src/fonts/PretendardVariable.woff2',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} font-sans`}
        style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}
      >
        <CoreProvider>
          <main style={{ flex: 1 }}>{children}</main>
          <Footer />
          <Modal components={MODAL_COMPONENTS} />
        </CoreProvider>
      </body>
    </html>
  );
}
